standalone_tags:
  [
    {id: 0, size: 0.087},
    {id: 1, size: 0.087},
    {id: 2, size: 0.087},
    {id: 3, size: 0.087},
    {id: 4, size: 0.1595},
    {id: 5, size: 0.1595},
    {id: 6, size: 0.1595},
  ]
tag_bundles: []