image_width: 640
image_height: 480
camera_name: video2
camera_matrix:
  rows: 3
  cols: 3
  data: [41635.42063,     0.     ,   310.44059,
             0.     ,  5597.97367,   295.23396,
             0.     ,     0.     ,     1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-12.247354, 5887.193036, 0.980493, -0.021114, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [43785.72656,     0.     ,   309.00498,     0.     ,
             0.     ,  5214.3667 ,   320.38609,     0.     ,
             0.     ,     0.     ,     1.     ,     0.     ]