obstacle_range: 3.0
raytrace_range: 3.0

# footprint: [[0, 0]]
# circular robot :)
robot_radius: 0.25
inflation_radius: 0.5 

observation_sources: point_cloud_sensor

point_cloud_sensor: {
  sensor_frame: d435_depth_optical_frame, 
  data_type: PointCloud2, 
  topic: /d435/depth/color/points, 
  marking: true, 
  clearing: true
}