obstacle_range: 3.0
raytrace_range: 3.5

footprint: [[-0.205, -0.155], [-0.205, 0.155], [0.077, 0.155], [0.077, -0.155]]
#robot_radius: 0.17

inflation_radius: 1.0
cost_scaling_factor: 3.0

map_type: costmap
observation_sources: dummy_scan # scan was first
#scan: {
#  sensor_frame: base_scan, 
#  data_type: LaserScan, 
#  topic: scan, 
#  marking: true, 
#  clearing: true
#  }
depth_cam: {
  sensor_frame: camera_depth_optical_frame, 
  data_type: PointCloud2, 
  topic: /camera/depth/points, 
  marking: true, 
  clearing: true,
  min_obstacle_height: -2.0,
  max_obstacle_height: 0.0
  }
dummy_scan: {
  sensor_frame: base_scan, 
  data_type: LaserScan, 
  topic: /scan_multi, 
  marking: true, 
  clearing: true
  }