obstacle_range: 3.0
raytrace_range: 3.5

footprint: [[-0.205, -0.155], [-0.205, 0.155], [0.077, 0.155], [0.077, -0.155]]
#robot_radius: 0.17

inflation_radius: 1.0
cost_scaling_factor: 3.0

map_type: costmap
observation_sources: scan depth_cam
scan: {
  sensor_frame: base_scan, 
  data_type: LaserScan, 
  topic: scan, 
  marking: true, 
  clearing: true
  }

depth_info: {
  sensor_frame: camera_depth_optical_frame, # same frame as og camera-produced pointcloud is in
  data_type: PointCloud2, 
  topic: /ana/point_cloud_hole_detection/hole_obs_cloud_out, 
  marking: true, 
  clearing: true,
  min_obstacle_height: -2.0,
  max_obstacle_height: 0.0
}
  
#depth_cam: {
#  sensor_frame: camera_depth_optical_frame, 
#  data_type: PointCloud2, 
#  topic: /camera/depth/points, 
#  marking: true, 
#  clearing: true,
#  min_obstacle_height: -2.0,
#  max_obstacle_height: 0.0
#  }
