global_costmap:
  global_frame: map
  robot_base_frame: robot_base
  update_frequency: 5.0
  static_map: false
  origin_x: -10
  origin_y: -10
  width: 20
  height: 20

# new
global_frame: map or smth
robot_base_frame: robot_base
update_frequency: 5.0
static_map: false