local_costmap:
  global_frame: tracking_cam
  robot_base_frame: robot_base
  update_frequency: 6.0
  publish_frequency: 6.0
  static_map: false
  rolling_window: true
  width: 8.0
  height: 8.0
  resolution: 0.05

# new
global_frame: robot_base
robot_base_frame: robot_base
update_frequency: 5.0
publish_frequency: 2.0
static_map: false
rolling_window: true
width: 6.0
height: 6.0
resolution: 0.05