local_costmap:
  global_frame: t265_odom_frame
  robot_base_frame: base_link
  update_frequency: 6.0
  publish_frequency: 6.0
  static_map: false
  rolling_window: true
  width: 8.0
  height: 8.0
  resolution: 0.05